version: 0.2
phases:
  install:
    commands:
      - echo Installing NGNIX
      - sudo apt-get update
      - sudo apt-get install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX


artifacts:
  files:
    - '**/*'